In [77]:
import pandas as pd # Library 
# To install it go on a command prompt and

In [78]:
my_series = pd.Series([23,56,78,89])

In [79]:
my_series

0    23
1    56
2    78
3    89
dtype: int64

In [80]:
my_series.index

RangeIndex(start=0, stop=4, step=1)

In [81]:
my_data_frame = pd.DataFrame({'age':[22,45,67,78],'height': [78,34,22,9]})

In [82]:
my_data_frame

   age  height
0   22      78
1   45      34
2   67      22
3   78       9

In [83]:
my_data_frame.index

RangeIndex(start=0, stop=4, step=1)

In [84]:
my_data_frame.iloc[1:4 ,0:2] # used when indexes are in integer form [start: end -1]

   age  height
1   45      34
2   67      22
3   78       9

In [85]:
names = pd.Series(['Safa','Abeeha','Pandas'], index=['a','b','c'])

In [86]:
names

a      Safa
b    Abeeha
c    Pandas
dtype: object

In [87]:
names.index

Index(['a', 'b', 'c'], dtype='object')

In [88]:
student = {'name':['Abeeha','Rehman','Ramsha'], 'age':[16,15,22]}
my_student = pd.DataFrame(student,index =["a","b","c"])

In [89]:
my_student

     name  age
a  Abeeha   16
b  Rehman   15
c  Ramsha   22

In [90]:
columns_name ={
    'name': 'Full Name' ,
    'age': 'Std_age'
}
my_student.rename(columns = columns_name , inplace = True)

In [91]:
my_student

  Full Name  Std_age
a    Abeeha       16
b    Rehman       15
c    Ramsha       22

In [92]:
my_student.columns

Index(['Full Name', 'Std_age'], dtype='object')

In [93]:
my_student.loc['a'] # use when index is in a texted form

Full Name    Abeeha
Std_age          16
Name: a, dtype: object

In [94]:
book = {'Book Name':["Harry Potter and the Philospher's Stone","Charlie and the chocolate factory","Famous Five"], 'Author Name':["Jk Rowling","Roald Dahl","Enid Blyton"],'Price':[3000,2000,1550],'Year':[1997,1964,1942]}
my_book = pd.DataFrame(book,index=['>1','>2','>3'])

In [95]:
my_book

                                  Book Name  Author Name  Price  Year
>1  Harry Potter and the Philospher's Stone   Jk Rowling   3000  1997
>2        Charlie and the chocolate factory   Roald Dahl   2000  1964
>3                              Famous Five  Enid Blyton   1550  1942

In [96]:
my_book.columns

Index(['Book Name', 'Author Name', 'Price', 'Year'], dtype='object')

In [97]:
names['b']

'Abeeha'

In [98]:
my_series[2]

78

In [99]:
my_student.loc['a':'c']

  Full Name  Std_age
a    Abeeha       16
b    Rehman       15
c    Ramsha       22

In [100]:
my_book['Author Name']

>1     Jk Rowling
>2     Roald Dahl
>3    Enid Blyton
Name: Author Name, dtype: object

In [102]:
books_data = pd.read_csv('Book 1.csv')
books_data

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008
...,...,...,...,...,...,...,...,...
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009

In [104]:
books_data.loc[50]

Film                 Life as We Know It
Genre                            Comedy
Lead Studio                 Independent
Audience score %                     62
Profitability                  2.530526
Rotten Tomatoes %                    28
Worldwide Gross                 $96.16
Year                               2010
Name: 50, dtype: object

Data preprocessing:
1 -> Data load
2 -> Columns
3 -> Data Cleaning 
A -> Remove Duplicates
B -> Null Values Handling 
C -> NaN Values Handling
D -> Removal of rows and columns
E -> Feature Engineering
In DataScience columns are known as "FEATURE".
4 -> Data Visualization
s -> Data Analysis

# Data Analyst
# Machine Learning
# Data scientist