In [36]:
import pandas as pd # Library 
# To install it go on a command prompt and

In [37]:
my_series = pd.Series([23,56,78,89])

In [38]:
my_series

0    23
1    56
2    78
3    89
dtype: int64

In [39]:
my_series.index

RangeIndex(start=0, stop=4, step=1)

In [40]:
my_data_frame = pd.DataFrame({'age':[22,45,67,78],'height': [78,34,22,9]})

In [41]:
my_data_frame

   age  height
0   22      78
1   45      34
2   67      22
3   78       9

In [42]:
my_data_frame.index

RangeIndex(start=0, stop=4, step=1)

In [63]:
my_data_frame.iloc[1:4 ,0:2] # used when indexes are in integer form [start: end -1]

   age  height
1   45      34
2   67      22
3   78       9

In [43]:
names = pd.Series(['Safa','Abeeha','Pandas'], index=['a','b','c'])

In [44]:
names

a      Safa
b    Abeeha
c    Pandas
dtype: object

In [45]:
names.index

Index(['a', 'b', 'c'], dtype='object')

In [52]:
student = {'name':['Abeeha','Rehman','Ramsha'], 'age':[16,15,22]}
my_student = pd.DataFrame(student,index =["a","b","c"])

In [53]:
my_student

     name  age
a  Abeeha   16
b  Rehman   15
c  Ramsha   22

In [54]:
columns_name ={
    'name': 'Full Name' ,
    'age': 'Std_age'
}
my_student.rename(columns = columns_name , inplace = True)

In [55]:
my_student

  Full Name  Std_age
a    Abeeha       16
b    Rehman       15
c    Ramsha       22

In [56]:
my_student.columns

Index(['Full Name', 'Std_age'], dtype='object')

In [57]:
my_student.loc['a'] # use when index is in a texted form

Full Name    Abeeha
Std_age          16
Name: a, dtype: object

In [64]:
book = {'Book Name':["Harry Potter and the Philospher's Stone","Charlie and the chocolate factory","Famous Five"], 'Author Name':["Jk Rowling","Roald Dahl","Enid Blyton"],'Price':[3000,2000,1550],'Year':[1997,1964,1942]}
my_book = pd.DataFrame(book,index=['>1','>2','>3'])

In [65]:
my_book

                                  Book Name  Author Name  Price  Year
>1  Harry Potter and the Philospher's Stone   Jk Rowling   3000  1997
>2        Charlie and the chocolate factory   Roald Dahl   2000  1964
>3                              Famous Five  Enid Blyton   1550  1942

In [ ]:
my_book.columns

Index(['Book Name', 'Author Name', 'Price', 'Year'], dtype='object')

In [ ]:
names['b']

'Abeeha'

In [ ]:
my_series[2]

78

In [ ]:
my_student['age']

*    16
*    15
*    22
Name: age, dtype: int64

In [61]:
my_student.loc['a':'c']

  Full Name  Std_age
a    Abeeha       16
b    Rehman       15
c    Ramsha       22

In [66]:
my_book['Author Name']

>1     Jk Rowling
>2     Roald Dahl
>3    Enid Blyton
Name: Author Name, dtype: object